/**
 * Copyright (C) 2015 Orange
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.francetelecom.clara.cloud.logicalmodel;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath:/com/francetelecom/clara/cloud/logicalmodel/application-context.xml"})
public class LogicalDeploymentRepositoryTest {

    @Autowired
    private LogicalDeploymentRepository logicalDeploymentRepository;

    @Before
    @Transactional
    public void setup() throws Exception {
        Assert.assertNotNull(logicalDeploymentRepository);
    }

    @Test
    @Transactional
    public void testPersist() {
        // test setup
        LogicalDeployment toBePersited = new LogicalDeployment();
        // test run
        logicalDeploymentRepository.save(toBePersited);
        // assertions
        Assert.assertNotNull("entity does not exist", logicalDeploymentRepository.findOne(toBePersited.getId()));
        logicalDeploymentRepository.flush();
    }

    @Test
    @Transactional
    public void testPersistDuplicateLabel() throws DataAccessException {
        // test setup
        LogicalDeployment toBePersited1 = new LogicalDeployment();
        System.out.println("toBePersited1" + toBePersited1.getId());
        LogicalDeployment toBePersited2 = new LogicalDeployment();
        System.out.println("toBePersited2" + toBePersited2.getId());
        // test run
        logicalDeploymentRepository.save(toBePersited1);
        logicalDeploymentRepository.save(toBePersited2);
        logicalDeploymentRepository.flush();
    }

    // logical deployment name is now auto-generated by system and setName method will become protected.
    // It will become impossible to modify name of ld
//	@Test(expected = DataAccessException.class)
//	@Transactional
//	public void testPersistDuplicateName() throws DataAccessException {
//		// test setup
//		LogicalDeployment toBePersited1 = new LogicalDeployment("ld-test1");
////        toBePersited1.setName("ld-test1");
//		System.out.println("toBePersited1" + toBePersited1.getId());
//		LogicalDeployment toBePersited2 = new LogicalDeployment("ld-test1");
////        toBePersited2.setName("ld-test1");
//		System.out.println("toBePersited2" + toBePersited2.getId());
//		// test run
//		logicalDeploymentRepository.persist(toBePersited1);
//		logicalDeploymentRepository.persist(toBePersited2);
//		logicalDeploymentRepository.flush();
//	}

    @Test
    @Transactional
    public void testRemove() {
        // test setup
        LogicalDeployment toBePersited = new LogicalDeployment();
        logicalDeploymentRepository.save(toBePersited);
        Assert.assertNotNull("entity does not exist", logicalDeploymentRepository.findOne(toBePersited.getId()));
        // test run
        logicalDeploymentRepository.delete(toBePersited);
        // assertions
        Assert.assertNull("entity should not exist", logicalDeploymentRepository.findOne(toBePersited.getId()));
        logicalDeploymentRepository.flush();
    }

    @Test
    @Transactional
    public void testFind() {
        // test setup
        LogicalDeployment toBePersited = new LogicalDeployment();
        logicalDeploymentRepository.save(toBePersited);
        // test run
        LogicalDeployment entity = logicalDeploymentRepository.findOne(toBePersited.getId());
        // assertions
        Assert.assertNotNull("entity does not exist", entity);
//		Assert.assertEquals("ld-test", entity.getLabel());

        //Assert.assertTrue("expected different instances to be read and returned", entity != toBePersited);
        Assert.assertEquals(toBePersited.getName(), entity.getName());
        Assert.assertEquals(toBePersited, entity);

        logicalDeploymentRepository.flush();
    }

    @Test
    @Transactional
    public void testMerge() {
        // test setup
        LogicalDeployment persisted = new LogicalDeployment();
        LogicalWebGUIService logicalService_persisted = new LogicalWebGUIService("LS1-test", persisted);
        logicalService_persisted.setContextRoot(new ContextRoot("/"));
        ProcessingNode jeeProcessing_persisted = new JeeProcessing("LEN1-test", persisted);

        logicalDeploymentRepository.save(persisted);

        LogicalDeployment logicalDeployment = logicalDeploymentRepository.findOne(persisted.getId());
//		logicalDeployment.setName("LD-XXX");

        LogicalWebGUIService logicalService1 = new LogicalWebGUIService("LS1-XXX", logicalDeployment);
        logicalService1.setContextRoot(new ContextRoot("/"));
        LogicalWebGUIService logicalService2 = new LogicalWebGUIService("LS2-XXX", logicalDeployment);
        logicalService2.setContextRoot(new ContextRoot("/"));
        ProcessingNode jeeProcessing1 = new JeeProcessing("LEN1-XXX", logicalDeployment);
        ProcessingNode jeeProcessing2 = new JeeProcessing("LEN2-XXX", logicalDeployment);

        logicalDeploymentRepository.save(logicalDeployment);
        logicalDeploymentRepository.flush();
        // test run
        LogicalDeployment entity = logicalDeploymentRepository.findOne(persisted.getId());
        // assertions
        Assert.assertNotNull("entity does not exist", entity);
        Assert.assertEquals(logicalDeployment.getName(), entity.getName());
        Assert.assertEquals(3, entity.listLogicalServices().size());
        Assert.assertEquals(3, entity.listProcessingNodes().size());
    }

    @Test
    @Transactional
    public void testFindAll() {
        // test setup
        LogicalDeployment toBePersited1 = new LogicalDeployment();
        LogicalDeployment toBePersited2 = new LogicalDeployment();
        LogicalDeployment toBePersited3 = new LogicalDeployment();
        logicalDeploymentRepository.save(toBePersited1);
        logicalDeploymentRepository.save(toBePersited2);
        logicalDeploymentRepository.save(toBePersited3);
        // test run
        List<LogicalDeployment> entities = logicalDeploymentRepository.findAll();
        // assertions
        Assert.assertNotNull("entities should not be null", entities);
        Assert.assertEquals("there should be 3 entities", 3, entities.size());
        logicalDeploymentRepository.flush();
    }


}
